pub const UTF8: u8 = 1;
pub const UNICODE: u8 = 2; /* unused */
pub const INTEGER: u8 = 3;
pub const FLOAT: u8 = 4;
pub const LONG: u8 = 5;
pub const DOUBLE: u8 = 6;
pub const CLASS: u8 = 7;
pub const STRING: u8 = 8;
pub const FIELD_REF: u8 = 9;
pub const METHOD_REF: u8 = 10;
pub const INTERFACE_METHOD_REF: u8 = 11;
pub const NAME_AND_TYPE: u8 = 12;
pub const METHOD_HANDLE: u8 = 15; // JSR 292
pub const METHOD_TYPE: u8 = 16; // JSR 292
pub const DYNAMIC: u8 = 17;
pub const INVOKE_DYNAMIC: u8 = 18;
pub const MODULE: u8 = 19;
pub const PACKAGE: u8 = 20;
pub const EXTERNAL_MAX: u8 = 20;
